const WATCH_GETTING_ITEMS = "mern-setup/ITEMS/WATCH_GETTING_ITEMS";
const GET_ITEMS_REQUESTED = "mern-setup/ITEMS/GET_ITEMS_REQUESTED";
const GET_ITEMS_FULFILLED = "mern-setup/ITEMS/GET_ITEMS_FULFILLED";
const GET_ITEMS_REJECTED = "mern-setup/ITEMS/GET_ITEMS_REJECTED";
const WATCH_POSTING_ITEM = "mern-setup/ITEMS/WATCH_POSTING_ITEM";
const POST_ITEM_REQUESTED = "mern-setup/ITEMS/POST_ITEM_REQUESTED";
const POST_ITEM_FULFILLED = "mern-setup/ITEMS/POST_ITEM_FULFILLED";
const POST_ITEM_REJECTED = "mern-setup/ITEMS/POST_ITEM_REJECTED";
const WATCH_DELETING_ITEM = "mern-setup/ITEMS/WATCH_DELETING_ITEM";
const DELETE_ITEM_REQUESTED = "mern-setup/ITEMS/DELETE_ITEM_REQUESTED";
const DELETE_ITEM_FULFILLED = "mern-setup/ITEMS/DELETE_ITEM_FULFILLED";
const DELETE_ITEM_REJECTED = "mern-setup/ITEMS/DELETE_ITEM_REJECTED";

export default {
  WATCH_GETTING_ITEMS,
  GET_ITEMS_REQUESTED,
  GET_ITEMS_FULFILLED,
  GET_ITEMS_REJECTED,
  WATCH_POSTING_ITEM,
  POST_ITEM_REQUESTED,
  POST_ITEM_FULFILLED,
  POST_ITEM_REJECTED,
  WATCH_DELETING_ITEM,
  DELETE_ITEM_REQUESTED,
  DELETE_ITEM_FULFILLED,
  DELETE_ITEM_REJECTED
};
